export const CountryCode = [
  { code: 'AF', name: 'Afghanistan', prefix: '+93' },
  { code: 'AL', name: 'Albania', prefix: '+355' },
  { code: 'DZ', name: 'Algeria', prefix: '+213' },
  { code: 'AD', name: 'Andorra', prefix: '+376' },
  { code: 'AO', name: 'Angola', prefix: '+244' },
  { code: 'AR', name: 'Argentina', prefix: '+54' },
  { code: 'AM', name: 'Armenia', prefix: '+374' },
  { code: 'AU', name: 'Australia', prefix: '+61' },
  { code: 'AT', name: 'Austria', prefix: '+43' },
  { code: 'AZ', name: 'Azerbaijan', prefix: '+994' },
  { code: 'BH', name: 'Bahrain', prefix: '+973' },
  { code: 'BD', name: 'Bangladesh', prefix: '+880' },
  { code: 'BY', name: 'Belarus', prefix: '+375' },
  { code: 'BE', name: 'Belgium', prefix: '+32' },
  { code: 'BJ', name: 'Benin', prefix: '+229' },
  { code: 'BO', name: 'Bolivia', prefix: '+591' },
  { code: 'BR', name: 'Brazil', prefix: '+55' },
  { code: 'BG', name: 'Bulgaria', prefix: '+359' },
  { code: 'CA', name: 'Canada', prefix: '+1' },
  { code: 'CL', name: 'Chile', prefix: '+56' },
  { code: 'CN', name: 'China', prefix: '+86' },
  { code: 'CO', name: 'Colombia', prefix: '+57' },
  { code: 'CD', name: 'Democratic Republic of the Congo', prefix: '+243' },
  { code: 'DK', name: 'Denmark', prefix: '+45' },
  { code: 'EG', name: 'Egypt', prefix: '+20' },
  { code: 'FI', name: 'Finland', prefix: '+358' },
  { code: 'FR', name: 'France', prefix: '+33' },
  { code: 'DE', name: 'Germany', prefix: '+49' },
  { code: 'GH', name: 'Ghana', prefix: '+233' },
  { code: 'GR', name: 'Greece', prefix: '+30' },
  { code: 'HK', name: 'Hong Kong', prefix: '+852' },
  { code: 'HU', name: 'Hungary', prefix: '+36' },
  { code: 'IS', name: 'Iceland', prefix: '+354' },
  { code: 'IN', name: 'India', prefix: '+91' },
  { code: 'ID', name: 'Indonesia', prefix: '+62' },
  { code: 'IR', name: 'Iran', prefix: '+98' },
  { code: 'IQ', name: 'Iraq', prefix: '+964' },
  { code: 'IE', name: 'Ireland', prefix: '+353' },
  { code: 'IL', name: 'Israel', prefix: '+972' },
  { code: 'IT', name: 'Italy', prefix: '+39' },
  { code: 'JP', name: 'Japan', prefix: '+81' },
  { code: 'JO', name: 'Jordan', prefix: '+962' },
  { code: 'KE', name: 'Kenya', prefix: '+254' },
  { code: 'KW', name: 'Kuwait', prefix: '+965' },
  { code: 'LB', name: 'Lebanon', prefix: '+961' },
  { code: 'LY', name: 'Libya', prefix: '+218' },
  { code: 'MY', name: 'Malaysia', prefix: '+60' },
  { code: 'MX', name: 'Mexico', prefix: '+52' },
  { code: 'MA', name: 'Morocco', prefix: '+212' },
  { code: 'NL', name: 'Netherlands', prefix: '+31' },
  { code: 'NZ', name: 'New Zealand', prefix: '+64' },
  { code: 'NG', name: 'Nigeria', prefix: '+234' },
  { code: 'NO', name: 'Norway', prefix: '+47' },
  { code: 'OM', name: 'Oman', prefix: '+968' },
  { code: 'PK', name: 'Pakistan', prefix: '+92' },
  { code: 'PE', name: 'Peru', prefix: '+51' },
  { code: 'PH', name: 'Philippines', prefix: '+63' },
  { code: 'PL', name: 'Poland', prefix: '+48' },
  { code: 'PT', name: 'Portugal', prefix: '+351' },
  { code: 'QA', name: 'Qatar', prefix: '+974' },
  { code: 'RO', name: 'Romania', prefix: '+40' },
  { code: 'RU', name: 'Russia', prefix: '+7' },
  { code: 'SA', name: 'Saudi Arabia', prefix: '+966' },
  { code: 'SN', name: 'Senegal', prefix: '+221' },
  { code: 'SG', name: 'Singapore', prefix: '+65' },
  { code: 'ZA', name: 'South Africa', prefix: '+27' },
  { code: 'KR', name: 'South Korea', prefix: '+82' },
  { code: 'ES', name: 'Spain', prefix: '+34' },
  { code: 'SE', name: 'Sweden', prefix: '+46' },
  { code: 'CH', name: 'Switzerland', prefix: '+41' },
  { code: 'TH', name: 'Thailand', prefix: '+66' },
  { code: 'TR', name: 'Turkey', prefix: '+90' },
  { code: 'UA', name: 'Ukraine', prefix: '+380' },
  { code: 'AE', name: 'United Arab Emirates', prefix: '+971' },
  { code: 'GB', name: 'United Kingdom', prefix: '+44' },
  { code: 'US', name: 'United States', prefix: '+1' },
  { code: 'VE', name: 'Venezuela', prefix: '+58' },
  { code: 'VN', name: 'Vietnam', prefix: '+84' },
  { code: 'YE', name: 'Yemen', prefix: '+967' },
  { code: 'ZM', name: 'Zambia', prefix: '+260' },
  { code: 'ZW', name: 'Zimbabwe', prefix: '+263' },
];

export const countryData = [
  { value: 'AF', label: 'Afghanistan' },
  { value: 'AL', label: 'Albania' },
  { value: 'DZ', label: 'Algeria' },
  { value: 'AD', label: 'Andorra' },
  { value: 'AO', label: 'Angola' },
  { value: 'AR', label: 'Argentina' },
  { value: 'AM', label: 'Armenia' },
  { value: 'AU', label: 'Australia' },
  { value: 'AT', label: 'Austria' },
  { value: 'AZ', label: 'Azerbaijan' },
  { value: 'BH', label: 'Bahrain' },
  { value: 'BD', label: 'Bangladesh' },
  { value: 'BY', label: 'Belarus' },
  { value: 'BE', label: 'Belgium' },
  { value: 'BZ', label: 'Belize' },
  { value: 'BJ', label: 'Benin' },
  { value: 'BO', label: 'Bolivia' },
  { value: 'BA', label: 'Bosnia and Herzegovina' },
  { value: 'BR', label: 'Brazil' },
  { value: 'BG', label: 'Bulgaria' },
  { value: 'BF', label: 'Burkina Faso' },
  { value: 'BI', label: 'Burundi' },
  { value: 'KH', label: 'Cambodia' },
  { value: 'CM', label: 'Cameroon' },
  { value: 'CA', label: 'Canada' },
  { value: 'CF', label: 'Central African Republic' },
  { value: 'TD', label: 'Chad' },
  { value: 'CL', label: 'Chile' },
  { value: 'CN', label: 'China' },
  { value: 'CO', label: 'Colombia' },
  { value: 'CG', label: 'Congo' },
  { value: 'CD', label: 'Democratic Republic of the Congo' },
  { value: 'CR', label: 'Costa Rica' },
  { value: 'HR', label: 'Croatia' },
  { value: 'CU', label: 'Cuba' },
  { value: 'CY', label: 'Cyprus' },
  { value: 'CZ', label: 'Czech Republic' },
  { value: 'DK', label: 'Denmark' },
  { value: 'DJ', label: 'Djibouti' },
  { value: 'DO', label: 'Dominican Republic' },
  { value: 'EC', label: 'Ecuador' },
  { value: 'EG', label: 'Egypt' },
  { value: 'SV', label: 'El Salvador' },
  { value: 'EE', label: 'Estonia' },
  { value: 'ET', label: 'Ethiopia' },
  { value: 'FI', label: 'Finland' },
  { value: 'FR', label: 'France' },
  { value: 'GA', label: 'Gabon' },
  { value: 'GM', label: 'Gambia' },
  { value: 'GE', label: 'Georgia' },
  { value: 'DE', label: 'Germany' },
  { value: 'GH', label: 'Ghana' },
  { value: 'GR', label: 'Greece' },
  { value: 'GT', label: 'Guatemala' },
  { value: 'GN', label: 'Guinea' },
  { value: 'HT', label: 'Haiti' },
  { value: 'HN', label: 'Honduras' },
  { value: 'HU', label: 'Hungary' },
  { value: 'IS', label: 'Iceland' },
  { value: 'IN', label: 'India' },
  { value: 'ID', label: 'Indonesia' },
  { value: 'IR', label: 'Iran' },
  { value: 'IQ', label: 'Iraq' },
  { value: 'IE', label: 'Ireland' },
  { value: 'IL', label: 'Israel' },
  { value: 'IT', label: 'Italy' },
  { value: 'JM', label: 'Jamaica' },
  { value: 'JP', label: 'Japan' },
  { value: 'JO', label: 'Jordan' },
  { value: 'KZ', label: 'Kazakhstan' },
  { value: 'KE', label: 'Kenya' },
  { value: 'KW', label: 'Kuwait' },
  { value: 'KG', label: 'Kyrgyzstan' },
  { value: 'LA', label: 'Laos' },
  { value: 'LV', label: 'Latvia' },
  { value: 'LB', label: 'Lebanon' },
  { value: 'LY', label: 'Libya' },
  { value: 'LT', label: 'Lithuania' },
  { value: 'LU', label: 'Luxembourg' },
  { value: 'MG', label: 'Madagascar' },
  { value: 'MY', label: 'Malaysia' },
  { value: 'ML', label: 'Mali' },
  { value: 'MT', label: 'Malta' },
  { value: 'MX', label: 'Mexico' },
  { value: 'MN', label: 'Mongolia' },
  { value: 'MA', label: 'Morocco' },
  { value: 'MZ', label: 'Mozambique' },
  { value: 'MM', label: 'Myanmar' },
  { value: 'NP', label: 'Nepal' },
  { value: 'NL', label: 'Netherlands' },
  { value: 'NZ', label: 'New Zealand' },
  { value: 'NI', label: 'Nicaragua' },
  { value: 'NE', label: 'Niger' },
  { value: 'NG', label: 'Nigeria' },
  { value: 'NO', label: 'Norway' },
  { value: 'OM', label: 'Oman' },
  { value: 'PK', label: 'Pakistan' },
  { value: 'PA', label: 'Panama' },
  { value: 'PE', label: 'Peru' },
  { value: 'PH', label: 'Philippines' },
  { value: 'PL', label: 'Poland' },
  { value: 'PT', label: 'Portugal' },
  { value: 'QA', label: 'Qatar' },
  { value: 'RO', label: 'Romania' },
  { value: 'RU', label: 'Russia' },
  { value: 'SA', label: 'Saudi Arabia' },
  { value: 'SN', label: 'Senegal' },
  { value: 'RS', label: 'Serbia' },
  { value: 'SG', label: 'Singapore' },
  { value: 'ZA', label: 'South Africa' },
  { value: 'KR', label: 'South Korea' },
  { value: 'ES', label: 'Spain' },
  { value: 'LK', label: 'Sri Lanka' },
  { value: 'SE', label: 'Sweden' },
  { value: 'CH', label: 'Switzerland' },
  { value: 'SY', label: 'Syria' },
  { value: 'TW', label: 'Taiwan' },
  { value: 'TZ', label: 'Tanzania' },
  { value: 'TH', label: 'Thailand' },
  { value: 'TN', label: 'Tunisia' },
  { value: 'TR', label: 'Turkey' },
  { value: 'UG', label: 'Uganda' },
  { value: 'UA', label: 'Ukraine' },
  { value: 'AE', label: 'United Arab Emirates' },
  { value: 'GB', label: 'United Kingdom' },
  { value: 'US', label: 'United States' },
  { value: 'UY', label: 'Uruguay' },
  { value: 'UZ', label: 'Uzbekistan' },
  { value: 'VE', label: 'Venezuela' },
  { value: 'VN', label: 'Vietnam' },
  { value: 'YE', label: 'Yemen' },
  { value: 'ZM', label: 'Zambia' },
  { value: 'ZW', label: 'Zimbabwe' },
];

export const ObjCountryCode = {
  AF: { name: 'Afghanistan', prefix: '+93' },
  AL: { name: 'Albania', prefix: '+355' },
  DZ: { name: 'Algeria', prefix: '+213' },
  AD: { name: 'Andorra', prefix: '+376' },
  AO: { name: 'Angola', prefix: '+244' },
  AR: { name: 'Argentina', prefix: '+54' },
  AM: { name: 'Armenia', prefix: '+374' },
  AU: { name: 'Australia', prefix: '+61' },
  AT: { name: 'Austria', prefix: '+43' },
  AZ: { name: 'Azerbaijan', prefix: '+994' },
  BH: { name: 'Bahrain', prefix: '+973' },
  BD: { name: 'Bangladesh', prefix: '+880' },
  BY: { name: 'Belarus', prefix: '+375' },
  BE: { name: 'Belgium', prefix: '+32' },
  BJ: { name: 'Benin', prefix: '+229' },
  BO: { name: 'Bolivia', prefix: '+591' },
  BR: { name: 'Brazil', prefix: '+55' },
  BG: { name: 'Bulgaria', prefix: '+359' },
  CA: { name: 'Canada', prefix: '+1' },
  CL: { name: 'Chile', prefix: '+56' },
  CN: { name: 'China', prefix: '+86' },
  CO: { name: 'Colombia', prefix: '+57' },
  CD: { name: 'Democratic Republic of the Congo', prefix: '+243' },
  DK: { name: 'Denmark', prefix: '+45' },
  EG: { name: 'Egypt', prefix: '+20' },
  FI: { name: 'Finland', prefix: '+358' },
  FR: { name: 'France', prefix: '+33' },
  DE: { name: 'Germany', prefix: '+49' },
  GH: { name: 'Ghana', prefix: '+233' },
  GR: { name: 'Greece', prefix: '+30' },
  HK: { name: 'Hong Kong', prefix: '+852' },
  HU: { name: 'Hungary', prefix: '+36' },
  IS: { name: 'Iceland', prefix: '+354' },
  IN: { name: 'India', prefix: '+91' },
  ID: { name: 'Indonesia', prefix: '+62' },
  IR: { name: 'Iran', prefix: '+98' },
  IQ: { name: 'Iraq', prefix: '+964' },
  IE: { name: 'Ireland', prefix: '+353' },
  IL: { name: 'Israel', prefix: '+972' },
  IT: { name: 'Italy', prefix: '+39' },
  JP: { name: 'Japan', prefix: '+81' },
  JO: { name: 'Jordan', prefix: '+962' },
  KE: { name: 'Kenya', prefix: '+254' },
  KW: { name: 'Kuwait', prefix: '+965' },
  LB: { name: 'Lebanon', prefix: '+961' },
  LY: { name: 'Libya', prefix: '+218' },
  MY: { name: 'Malaysia', prefix: '+60' },
  MX: { name: 'Mexico', prefix: '+52' },
  MA: { name: 'Morocco', prefix: '+212' },
  NL: { name: 'Netherlands', prefix: '+31' },
  NZ: { name: 'New Zealand', prefix: '+64' },
  NG: { name: 'Nigeria', prefix: '+234' },
  NO: { name: 'Norway', prefix: '+47' },
  OM: { name: 'Oman', prefix: '+968' },
  PK: { name: 'Pakistan', prefix: '+92' },
  PE: { name: 'Peru', prefix: '+51' },
  PH: { name: 'Philippines', prefix: '+63' },
  PL: { name: 'Poland', prefix: '+48' },
  PT: { name: 'Portugal', prefix: '+351' },
  QA: { name: 'Qatar', prefix: '+974' },
  RO: { name: 'Romania', prefix: '+40' },
  RU: { name: 'Russia', prefix: '+7' },
  SA: { name: 'Saudi Arabia', prefix: '+966' },
  SN: { name: 'Senegal', prefix: '+221' },
  SG: { name: 'Singapore', prefix: '+65' },
  ZA: { name: 'South Africa', prefix: '+27' },
  KR: { name: 'South Korea', prefix: '+82' },
  ES: { name: 'Spain', prefix: '+34' },
  SE: { name: 'Sweden', prefix: '+46' },
  CH: { name: 'Switzerland', prefix: '+41' },
  TH: { name: 'Thailand', prefix: '+66' },
  TR: { name: 'Turkey', prefix: '+90' },
  UA: { name: 'Ukraine', prefix: '+380' },
  AE: { name: 'United Arab Emirates', prefix: '+971' },
  GB: { name: 'United Kingdom', prefix: '+44' },
  US: { name: 'United States', prefix: '+1' },
  VE: { name: 'Venezuela', prefix: '+58' },
  VN: { name: 'Vietnam', prefix: '+84' },
  YE: { name: 'Yemen', prefix: '+967' },
  ZM: { name: 'Zambia', prefix: '+260' },
  ZW: { name: 'Zimbabwe', prefix: '+263' },
};
